package chaos.core.model;

import chaos.api.annoatation.ApiField;

import java.io.Serializable;

public class ConfigModel_ implements Serializable {
    @ApiField("id///")
    private Integer id;

    /**
     * key唯一性
     */
    @ApiField("keyMark/key唯一性//")
    private String keyMark;

    @ApiField("title///")
    private String title;

    /**
     * 详细说明
     */
    @ApiField("description/详细说明//")
    private String description;

    /**
     * 内容建议使用json格式
     */
    @ApiField("value/内容建议使用json格式//")
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config_
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * key唯一性
     */
    public String getKeyMark() {
        return keyMark;
    }

    /**
     * key唯一性
     */
    public void setKeyMark(String keyMark) {
        this.keyMark = keyMark == null ? null : keyMark.trim();
    }

    /**
     * 
     */
    public String getTitle() {
        return title;
    }

    /**
     * 
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 详细说明
     */
    public String getDescription() {
        return description;
    }

    /**
     * 详细说明
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * 内容建议使用json格式
     */
    public String getValue() {
        return value;
    }

    /**
     * 内容建议使用json格式
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}