package chaos.core.model;

import chaos.api.annoatation.ApiField;

import java.io.Serializable;

public class RegionModel implements Serializable {
    @ApiField("id///")
    private Short id;

    /**
     * 名字
     */
    @ApiField("name/名字//")
    private String name;

    /**
     * 区号
     */
    @ApiField("code/区号//")
    private Short code;

    /**
     * 上级id
     */
    @ApiField("parentId/上级id//")
    private Short parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table common_region
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     */
    public Short getId() {
        return id;
    }

    /**
     * 
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * 名字
     */
    public String getName() {
        return name;
    }

    /**
     * 名字
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 区号
     */
    public Short getCode() {
        return code;
    }

    /**
     * 区号
     */
    public void setCode(Short code) {
        this.code = code;
    }

    /**
     * 上级id
     */
    public Short getParentId() {
        return parentId;
    }

    /**
     * 上级id
     */
    public void setParentId(Short parentId) {
        this.parentId = parentId;
    }
}