package chaos.core.model;

import chaos.api.annoatation.ApiField;

import java.io.Serializable;

public class SPermission implements Serializable {

    @ApiField("id///")
    private Long id;

    /**
     * url地址
     */
    @ApiField("url/url地址//")
    private String url;

    /**
     * url描述
     */
    @ApiField("name/url描述//")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_permission
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     */
    public Long getId() {
        return id;
    }

    /**
     *
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * url地址
     */
    public String getUrl() {
        return url;
    }

    /**
     * url地址
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * url描述
     */
    public String getName() {
        return name;
    }

    /**
     * url描述
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}