package chaos.core.model;

import chaos.api.annoatation.ApiField;

import java.io.Serializable;

public class SRolePermission implements Serializable {
    @ApiField("id///")
    private Long id;

    /**
     * 角色ID
     */
    @ApiField("rid/角色ID//")
    private Long rid;

    /**
     * 权限ID
     */
    @ApiField("pid/权限ID//")
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_role_permission
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 角色ID
     */
    public Long getRid() {
        return rid;
    }

    /**
     * 角色ID
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * 权限ID
     */
    public Long getPid() {
        return pid;
    }

    /**
     * 权限ID
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }
}