package chaos.core.model;

import chaos.api.annoatation.ApiField;

import java.io.Serializable;

public class SRole implements Serializable {
    @ApiField("id///")
    private Long id;

    /**
     * 角色名称
     */
    @ApiField("name/角色名称//")
    private String name;

    /**
     * 角色状态 0：正常 -1：冻结
     */
    @ApiField("status/角色状态 0：正常 -1：冻结//")
    private Short status;

    /**
     * 角色标识
     */
    @ApiField("mark/角色标识//")
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 角色名称
     */
    public String getName() {
        return name;
    }

    /**
     * 角色名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 角色状态 0：正常 -1：冻结
     */
    public Short getStatus() {
        return status;
    }

    /**
     * 角色状态 0：正常 -1：冻结
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * 角色标识
     */
    public String getMark() {
        return mark;
    }

    /**
     * 角色标识
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }
}