package chaos.core.dao;

import chaos.core.model.ConfigModel;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ConfigModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_config
     *
     * @mbg.generated
     */
    @Delete({
        "delete from common_config",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_config
     *
     * @mbg.generated
     */
    @Insert({
        "insert into common_config (key_mark, title, ",
        "description, value)",
        "values (#{keyMark,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{value,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ConfigModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_config
     *
     * @mbg.generated
     */
    int insertSelective(ConfigModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_config
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, key_mark, title, description, value",
        "from common_config",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("chaos.core.dao.ConfigModelMapper.ResultMapWithBLOBs")
    ConfigModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConfigModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_config
     *
     * @mbg.generated
     */
    @Update({
        "update common_config",
        "set key_mark = #{keyMark,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "value = #{value,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(ConfigModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_config
     *
     * @mbg.generated
     */
    @Update({
        "update common_config",
        "set key_mark = #{keyMark,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ConfigModel record);
}