package chaos.core.dao;

import chaos.core.model.ConfigModel_;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ConfigModel_Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_
     *
     * @mbg.generated
     */
    @Delete({
        "delete from config_",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_
     *
     * @mbg.generated
     */
    @Insert({
        "insert into config_ (key_mark, title, ",
        "description, value)",
        "values (#{keyMark,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{value,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ConfigModel_ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_
     *
     * @mbg.generated
     */
    int insertSelective(ConfigModel_ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, key_mark, title, description, value",
        "from config_",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("chaos.core.dao.ConfigModel_Mapper.ResultMapWithBLOBs")
    ConfigModel_ selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConfigModel_ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_
     *
     * @mbg.generated
     */
    @Update({
        "update config_",
        "set key_mark = #{keyMark,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "value = #{value,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(ConfigModel_ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_
     *
     * @mbg.generated
     */
    @Update({
        "update config_",
        "set key_mark = #{keyMark,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ConfigModel_ record);
}