package chaos.core.dao;

import chaos.core.model.ExceptionModel;
import org.apache.ibatis.annotations.Insert;

public interface ExceptionModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_exceptions
     *
     * @mbg.generated
     */
    @Insert({
        "insert into common_exceptions (ip, user_id, ",
        "title, device, c_date, ",
        "context)",
        "values (#{ip,jdbcType=VARCHAR}, #{userId,jdbcType=BIGINT}, ",
        "#{title,jdbcType=VARCHAR}, #{device,jdbcType=VARCHAR}, #{cDate,jdbcType=BIGINT}, ",
        "#{context,jdbcType=LONGVARCHAR})"
    })
    int insert(ExceptionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_exceptions
     *
     * @mbg.generated
     */
    int insertSelective(ExceptionModel record);
}