package chaos.core.dao;

import chaos.core.model.LogModel;
import org.apache.ibatis.annotations.Insert;

public interface LogModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_logs
     *
     * @mbg.generated
     */
    @Insert({
        "insert into common_logs (user_id, targetTable, ",
        "type, description, ",
        "ip, c_date)",
        "values (#{userId,jdbcType=BIGINT}, #{targettable,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=INTEGER}, #{description,jdbcType=VARCHAR}, ",
        "#{ip,jdbcType=VARCHAR}, #{cDate,jdbcType=BIGINT})"
    })
    int insert(LogModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_logs
     *
     * @mbg.generated
     */
    int insertSelective(LogModel record);
}