package chaos.core.dao;

import chaos.core.model.LogModel_;
import org.apache.ibatis.annotations.Insert;

public interface LogModel_Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs_
     *
     * @mbg.generated
     */
    @Insert({
        "insert into logs_ (user_id, targetTable, ",
        "type, description, ",
        "ip, c_date)",
        "values (#{userId,jdbcType=BIGINT}, #{targettable,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=INTEGER}, #{description,jdbcType=VARCHAR}, ",
        "#{ip,jdbcType=VARCHAR}, #{cDate,jdbcType=BIGINT})"
    })
    int insert(LogModel_ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs_
     *
     * @mbg.generated
     */
    int insertSelective(LogModel_ record);
}