package chaos.core.dao;

import chaos.core.model.SAccountRole;
import org.apache.ibatis.annotations.Insert;

public interface SAccountRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_account_role
     *
     * @mbg.generated
     */
    @Insert({
        "insert into s_account_role (a_id, r_id)",
        "values (#{aId,jdbcType=VARCHAR}, #{rId,jdbcType=BIGINT})"
    })
    int insert(SAccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_account_role
     *
     * @mbg.generated
     */
    int insertSelective(SAccountRole record);
}