package chaos.core.dao;

import chaos.core.model.SRole;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface SRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    @Delete({
            "delete from s_role",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    @Insert({
            "insert into s_role (name, status, ",
            "mark)",
            "values (#{name,jdbcType=VARCHAR}, #{status,jdbcType=SMALLINT}, ",
            "#{mark,jdbcType=VARCHAR})"
    })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    int insertSelective(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "id, name, status, mark",
            "from s_role",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("chaos.core.dao.SRoleMapper.BaseResultMap")
    SRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    @Update({
            "update s_role",
            "set name = #{name,jdbcType=VARCHAR},",
            "status = #{status,jdbcType=SMALLINT},",
            "mark = #{mark,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SRole record);


    @Select({"SELECT ",
            "r.* FROM s_role  as r LEFT JOIN s_account_role as a ON a.r_id = r.id ",
            "WHERE a.a_id=#{aId}"
    })
    @ResultMap("chaos.core.dao.SRoleMapper.BaseResultMap")
    List<SRole> selectListByAid(String aId);

    @Select({
            "select",
            "id, name, status, mark",
            "from s_role"
    })
    @ResultMap("chaos.core.dao.SRoleMapper.BaseResultMap")
    List<SRole> selectAll(String aId);
}