package chaos.core.dao;

import chaos.core.model.SRolePermission;
import org.apache.ibatis.annotations.Insert;

public interface SRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_permission
     *
     * @mbg.generated
     */
    @Insert({
        "insert into s_role_permission (rid, pid)",
        "values (#{rid,jdbcType=BIGINT}, #{pid,jdbcType=BIGINT})"
    })
    int insert(SRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_permission
     *
     * @mbg.generated
     */
    int insertSelective(SRolePermission record);
}